baseURL = "https://igorpejic.com"
languageCode = "en-us"
title = "Igor Pejic's Blog"
theme = "archie"
copyright = "© Igor Pejic"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate = 4 # articles per page

[params]
mode = "auto" # color-mode → light,dark,toggle or auto
useCDN = false # don't use CDNs for fonts and icons, instead serve them locally.
# subtitle = "Personal blog and portfolio"
mathjax = true # enable MathJax support
katex = true # enable KaTeX support
customcss = ["css/custom.css"]

# Social Tags
[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/igorpejic/"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/igorpejic"

# Main menu Items
[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Blog"
url = "/posts"
weight = 2


[[menu.main]]
name = "Contact"
url = "/contact"
weight = 3